Repository XRTK/com.xrtk.sdk, pull requests merged in 2019-08, with the labels that each got.

#57 Pointer Locking Fixes
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/BaseCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/LinePointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/UX/Pointers/BaseControllerPointerInspector.cs
Labels: enhancement

#60 Dev/bounding box accessors
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Labels: In Progress

#62 fix/wireframe
  XRTK.SDK/Packages/com.xrtk.sdk/StandardAssets/Materials/Wireframe.mat
  XRTK.SDK/Packages/com.xrtk.sdk/StandardAssets/Materials/WireframeBlue.mat
Labels: Ready for review

#63 Release 0.1.10
  XRTK.SDK/Assets/XRTK.Generated/CustomProfiles/MixedRealityPackageSettings.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/BaseInputHandler.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/BoundingBox/BoundingBox.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/BaseCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/LinePointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/UX/Pointers/BaseControllerPointerInspector.cs
  XRTK.SDK/Packages/com.xrtk.sdk/StandardAssets/Materials/Wireframe.mat
  XRTK.SDK/Packages/com.xrtk.sdk/StandardAssets/Materials/WireframeBlue.mat
  XRTK.SDK/Packages/com.xrtk.sdk/package.json
  XRTK.SDK/Packages/manifest.json
  XRTK.SDK/ProjectSettings/EditorBuildSettings.asset
  XRTK.SDK/ProjectSettings/ProjectVersion.txt
Labels: Ready for review

#69 dev/controller-refactor
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Controllers/DefaultMixedRealityControllerVisualizer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/package.json
  XRTK.SDK/Packages/manifest.json
Labels: Ready for review

#67 Dev/manipulation polish
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs
Labels: Ready for review

#71 Changes from XRTK.Core 0.1.17
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/GazeProvider.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/BaseFocusHandler.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/DragAndDropHandler.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/BaseCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/CursorModifier.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/TeleportCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/LinePointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/TeleportPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/TouchPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/package.json
  XRTK.SDK/Packages/manifest.json
Labels: Breaking Change, Ready for review
