Repository XRTK/com.xrtk.sdk, pull requests merged in 2020-01, with the labels that each got.

#124 cleaned up the diagnostics prefab a bit to make sure it looks nice
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Prefabs/DefaultDiagnosticsWindow.prefab
Labels: Bug

#125 Fix default data providers profile due to name change
  XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/package.json
Labels: Breaking Change

#126 Fixed global listener unregistration
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/InputSystemGlobalListener.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/BaseCursor.cs
Labels: Bug, Ready for review

#127 Fix DestroyImmediate being called in editor playmode causing Unity ev…
  XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ControllerPoseSynchronizer.cs
Labels: Bug, Ready for review
