Repository XRTK/com.xrtk.sdk, pull requests merged in 2020-05, with the labels that each got.

#169 fixed left generic controller type reference
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/GenericOpenVRController/LeftGenericOpenVRControllerProfile.asset
Labels: Bug, Ready for review

#176 Change requests/sdk installer
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/SDKPackageInstaller.cs
Labels: Ready for review

#174 Updated GUID regeneration for SDK
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/SDKPackageInstaller.cs
Labels: Bug, Ready for review

#178 cleaned up sdk a bit
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/Input/Handlers/ControllerPoseSynchronizerInspector.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/UX/Pointers/LinePointerInspector.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/UX/Pointers/DefaultControllerPointer.prefab
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Audio/Influencers/AudioOccluder.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/GazeProvider.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/GazeProvider.cs.meta
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/Handlers/DragAndDropHandler.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/Handlers/SpeechInputHandler.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/Handlers/TeleportHotSpot.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/InputSystemGlobalListener.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Collections/ScatterObjectCollection.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Controllers/DefaultMixedRealityControllerVisualizer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Controllers/Hands/BaseHandControllerVisualizer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Controllers/Hands/HandControllerMeshVisualizer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Controllers/WindowsMixedRealityControllerVisualizer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Cursors/AnimatedCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Cursors/InteractiveMeshCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Cursors/MeshCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Cursors/ObjectCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Cursors/SpriteCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Cursors/TeleportCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/ParabolicTeleportPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/TouchPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Receivers/InteractionReceiver.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Tooltips/ToolTip.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Tooltips/ToolTipBackgroundBlob.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Tooltips/ToolTipBackgroundCorners.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Tooltips/ToolTipBackgroundMesh.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Tooltips/ToolTipSpawner.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Tooltips/TooltipEnums/ConnectorFollowType.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Utilities/InteractableHighlight.cs
Labels: Breaking Change, Ready for review

#180 fixed guid references to diagnostics prefab
  XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/Diagnostics/DefaultDiagnosticsWindow.prefab
Labels: Bug, Ready for review

#181 Added preview package capabilities
  .gitignore
  XRTK.SDK/Assets/XRTK.Generated.meta
  XRTK.SDK/Assets/XRTK.Generated/SDK.meta
  XRTK.SDK/Assets/XRTK.Generated/SymbolicLinkSettings.asset
  XRTK.SDK/Assets/XRTK.Generated/SymbolicLinkSettings.asset.meta
  XRTK.SDK/Packages/com.xrtk.sdk/package.json
  XRTK.SDK/Packages/manifest.json
  azure-pipelines.yml
  azure_pipelines/common.yml
  azure_pipelines/stages/publish.yml
  azure_pipelines/stages/steps/build-docs.yml
  azure_pipelines/stages/steps/build-unity-player.yml
  azure_pipelines/stages/steps/export-package-seed.yml
  azure_pipelines/stages/steps/install-unity.yml
  azure_pipelines/stages/steps/return-unity-license.yml
  azure_pipelines/stages/steps/run-unity-tests.yml
  azure_pipelines/stages/steps/upm-package-info.yml
  azure_pipelines/stages/unity-build.yml
Labels: Enhancement, Ready for review

#183 updated github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/request_for_information.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Enhancement, Ready for review

#184 Move platform profiles from SDK to WMR package
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WMRControllerDataProviderProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WMRControllerDataProviderProfile.asset.meta
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityHandControllerDataProviderProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityHandControllerDataProviderProfile.asset.meta
Labels: Ready for review

#168 changes for near pointer interactions using collision
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/UX/Pointers/BaseControllerPointerInspector.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/MixedRealityInputSystemProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/Handlers/ManipulationHandler.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
  XRTK.SDK/Packages/manifest.json
Labels: Breaking Change, Ready for review

#185 Updated package installer
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/SDKPackageInstaller.cs
Labels: Bug, Ready for review

#186 Update default near clip plane for transparent display
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/CameraSystem/MixedRealityCameraDataProviderProfile.asset
Labels: Ready for review

#187 Fix/mouse pointer
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/MouseController/MousePointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/MouseController/MousePointerProfile.asset.meta
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/MouseController/SpatialMousePositionProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/MousePointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/TouchPointer.cs
Labels: Ready for review

#188 Updated teleport pointer references on controllers, fixed wmr input
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/GenericOpenVRController/Left/SpatialPointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/GenericOpenVRController/Right/SpatialPointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/OculusGoController/SpatialPointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/OculusTouchController/Left/SpatialPointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/OculusTouchController/Right/SpatialPointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/ViveWandController/Left/SpatialPointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/ViveWandController/Right/SpatialPointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Left/InvertDualAxisProcessor.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Left/SpatialPointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Left/ThumbstickPositionProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Left/TriggerPress(Select)Profile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Right/GripPressProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Right/InvertDualAxisProcessor.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Right/SpatialPointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Right/TriggerPress(Select)Profile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/Pointers/TeleportPointerProfile.asset
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/Pointers/TeleportPointerProfile.asset.meta
Labels: Bug, Enhancement, Ready for review

#189 Mouse input/visual polish
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/UX/Pointers/MousePointerInspector.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/UX/Cursors/MouseCursor.prefab
  XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/UX/Pointers/MousePointer.prefab
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Cursors/MeshCursor.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/MousePointer.cs
Labels: Enhancement, Ready for review

#191 A few more tweaks to the mouse pointer
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/MousePointer.cs
Labels: Enhancement, Ready for review

#192 Change requests/hand input
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/RecordedPoses/FlatHandPoseData.json
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/RecordedPoses/GrabHandPoseData.json
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/RecordedPoses/OpenHandPoseData.json
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/RecordedPoses/PinchHandPoseData.json
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/RecordedPoses/PinchSteadyWristHandPoseData.json
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/RecordedPoses/PokeHandPoseData.json
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/RecordedPoses/ThumbsUpHandPoseData.json
  XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/RecordedPoses/VictoryHandPoseData.json
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/HandDataRecorder.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/HandNearPointer.cs
Labels: Bug, Ready for review

#193 Small hand pointer update
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/Input/Handlers/ControllerPoseSynchronizerInspector.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/UX/Pointers/BaseControllerPointerInspector.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/UX/Pointers/HandNearPointerInspector.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/UX/Pointers/HandNearPointerInspector.cs.meta
  XRTK.SDK/Packages/com.xrtk.sdk/Editor/UX/Pointers/LinePointerInspector.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/HandNearPointer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/HandSpatialPointer.cs
Labels: Ready for review

#195 updated null and destroy calls with better extension
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/Handlers/ControllerPoseSynchronizer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Controllers/Hands/BaseHandControllerVisualizer.cs
  XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
  XRTK.SDK/Packages/manifest.json
Labels: Ready for review
